import { t } from '@/i18n'
export default {
  id: 'jaded',
  title: t('翡翠 Jaded'),
  desc: '暗色翡翠绿主题 — 毛玻璃顶栏、渐变文字、左图右文卡片、文章衬线体',
  version: '1.0.0',
  pages: ['posts'],
  tokens: {
    '--th-jade': t('翡翠绿强调色'),
    '--th-jade-l': t('翡翠绿浅'),
    '--th-jade-d': t('翡翠绿深'),
    '--th-jade-glow': t('翡翠绿光晕'),
    '--th-jade-subtle': t('翡翠绿极浅'),
    '--th-ink': t('最深底'),
    '--th-ink-1': t('深底一级'),
    '--th-ink-2': t('深底二级（卡片）'),
    '--th-ink-3': t('深底三级'),
    '--th-text': t('主文字'),
    '--th-text-2': t('次要文字'),
    '--th-text-3': t('弱化文字'),
    '--th-border': t('分隔线'),
    '--th-border-h': t('分隔线hover'),
    '--th-r': t('大圆角'),
    '--th-rs': t('小圆角'),
    '--th-rxs': t('最小圆角'),
    '--th-font': t('正文字体'),
    '--th-font-serif': t('衬线字体'),
    '--th-font-mono': t('等宽字体'),
  },
  ui: { themeSwitcher: true },
  dataSources: ['blog'],
  dataScope: 'shared',
}