import { t } from '@/i18n'
export default {
  id: 'chenxi',
  title: t('晨曦笔记 Chenxi'),
  desc: '温暖渐变博客主题 — 玫粉主调、彩虹渐变 Hero、左图右文卡片、毛玻璃顶栏',
  version: '1.0.0',
  pages: ['posts'],
  tokens: {
    '--th-primary': t('主色玫粉'),
    '--th-primary-l': t('玫粉浅'),
    '--th-primary-d': t('玫粉深'),
    '--th-accent': t('辅色紫蓝'),
    '--th-accent-l': t('紫蓝浅'),
    '--th-warm': t('暖橘'),
    '--th-warm-l': t('暖橘浅'),
    '--th-mint': t('薄荷绿'),
    '--th-mint-l': t('薄荷绿浅'),
    '--th-sky': t('天蓝'),
    '--th-sky-l': t('天蓝浅'),
    '--th-ink': t('最深文字'),
    '--th-text': t('正文'),
    '--th-text-2': t('次要文字'),
    '--th-text-3': t('弱化文字'),
    '--th-bg': t('页面底'),
    '--th-bg-2': t('次底色'),
    '--th-bg-3': t('三级底色'),
    '--th-card': t('卡片底'),
    '--th-line': t('分隔线'),
    '--th-line-h': t('分隔线hover'),
    '--th-r': t('大圆角'),
    '--th-rs': t('小圆角'),
    '--th-rxs': t('最小圆角'),
    '--th-font': t('主题字体'),
  },
  ui: { themeSwitcher: true },
  dataSources: ['blog'],
  dataScope: 'shared',
}