import { t } from '@/i18n'
export default {
  id: 'zhicang',
  title: t('知藏 Zhicang'),
  desc: '资源课程分享主题 — 靛蓝主调、学习路径追踪、课程进度条、资源卡片网格',
  version: '1.0.0',
  pages: ['posts'],
  tokens: {
    '--th-indigo': t('主色靛蓝'),
    '--th-indigo-l': t('靛蓝浅'),
    '--th-indigo-d': t('靛蓝深'),
    '--th-indigo-bg': t('靛蓝极浅底'),
    '--th-indigo-glow': t('靛蓝光晕'),
    '--th-peach': t('辅色暖橘'),
    '--th-peach-bg': t('暖橘底'),
    '--th-rose': t('玫红'),
    '--th-rose-bg': t('玫红底'),
    '--th-emerald': t('翡翠绿'),
    '--th-emerald-bg': t('翡翠绿底'),
    '--th-sky': t('天蓝'),
    '--th-sky-bg': t('天蓝底'),
    '--th-ink': t('最深文字'),
    '--th-ink-2': t('深文字'),
    '--th-text': t('正文'),
    '--th-text-2': t('次要文字'),
    '--th-text-3': t('弱化文字'),
    '--th-bg': t('页面底'),
    '--th-bg-2': t('次底色'),
    '--th-card': t('卡片底'),
    '--th-line': t('分隔线'),
    '--th-line-h': t('分隔线hover'),
    '--th-r': t('大圆角'),
    '--th-rs': t('小圆角'),
    '--th-rxs': t('最小圆角'),
    '--th-font': t('主题字体'),
  },
  ui: { themeSwitcher: true },
  dataSources: ['blog'],
  dataScope: 'shared',
}