import { t } from '@/i18n'
export default {
  id: 'aiknav',
  title: t('好站导航 AikNav'),
  desc: '导航站风格 — 蓝色主调卡片网格，左侧分类树与热门榜单',
  version: '1.0.0',
  pages: ['posts'],
  tokens: {
    '--th-blue': t('主色蓝'),
    '--th-blue-l': t('主色蓝浅'),
    '--th-blue-bg': t('主色蓝极浅底'),
    '--th-ink': t('正文色'),
    '--th-ink-2': t('次要文字'),
    '--th-ink-3': t('弱化文字'),
    '--th-ink-4': t('最弱文字'),
    '--th-paper': t('页面底'),
    '--th-card': t('卡片底'),
    '--th-line': t('分隔线'),
    '--th-line-h': t('分隔线hover'),
    '--th-green': t('绿色标签'),
    '--th-green-bg': t('绿色标签底'),
    '--th-orange': t('橙色标签'),
    '--th-orange-bg': t('橙色标签底'),
    '--th-purple': t('紫色标签'),
    '--th-purple-bg': t('紫色标签底'),
    '--th-pink': t('粉色标签'),
    '--th-pink-bg': t('粉色标签底'),
    '--th-cyan': t('青色标签'),
    '--th-cyan-bg': t('青色标签底'),
    '--th-r': t('大圆角'),
    '--th-rs': t('小圆角'),
    '--th-font': t('主题字体'),
  },
  ui: { themeSwitcher: true },
  dataSources: ['blog'],
  dataScope: 'shared',
}